instance_groups:
- azs:
  - z1
  - z2
  - z3
  env:
    persistent_disk_fs: xfs
  instances: 3
  jobs:
  - consumes:
      config-server:
        from: mdbconf-shared-server
    name: cfgsvr
    properties:
      admin_password: myP@ssword
      admin_username: smarsh
      port: 23758
      replication:
        enable: 1
        key: ((keyfile_content))
        replica_set_name: mongo-config-shared
      require_ssl: 1
      root_password: rootpassword
      root_username: admin
      server_certificate:
        certificate: ((mongo_ca.certificate))
        private_key: ((mongo_ca.private_key))
    provides:
      config-server:
        as: mdbconf-shared-server
    release: mongodb-services
  name: mdbconf-shared
  networks:
  - name: default
  release: mongodb-services
  stemcell: ubuntu
  vm_type: default
- azs:
  - z1
  - z2
  - z3
  instances: 1
  jobs:
  - consumes:
      config-server:
        from: mdbconf-shared-server
      routing-service:
        from: mongos-shared-router
    name: mongos
    properties:
      port: 23757
    provides:
      routing-service:
        as: mongos-shared-router
    release: mongodb-services
  name: mongos-shared
  networks:
  - name: default
  stemcell: ubuntu
  vm_type: default
- azs:
  - z1
  - z2
  - z3
  env:
    persistent_disk_fs: xfs
  instances: 3
  jobs:
  - consumes:
      config-server:
        from: mdbconf-shared-server
      routing-service:
        from: mongos-shared-router
      shard-server:
        from: mdb-shared
    name: shardsvr
    properties:
      port: 23757
      replication:
        replica_set_name: mongo-data-shared
    provides:
      shard-server:
        as: mdb-shared
    release: mongodb-services
  name: mdb-shared
  networks:
  - name: default
  release: mongodb-services
  stemcell: ubuntu
  vm_type: default
name: mongodb
releases:
- name: mongodb-services
  version: latest
stemcells:
- alias: ubuntu
  os: ubuntu-xenial
  version: latest
update:
  canaries: 1
  canary_watch_time: 30000-240000
  max_in_flight: 1
  serial: false
  update_watch_time: 30000-240000
variables:
  - name: root_password
    type: password
  - name: keyfile_content
    type: password
    options:
      length: 200
  - name: mongo_ca
    type: certificate
    options:
      is_ca: true
      common_name: MongoDB CA
features:
  use_dns_addresses: false
