anchors:
  smarsh_releases_bucket: &smarsh_releases_bucket
    bucket: smarsh-bosh-releases
    access_key_id: ((smarsh_bosh_releases_bucket_access_key_id))
    secret_access_key: ((smarsh_bosh_releases_bucket_secret_access_key))

resources:
- name: mongodb_release
  type: s3
  source:
    << : *smarsh_releases_bucket
    regexp: mongodb/mongodb(.*).tgz

- name: xenial_stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent

- name: old_xenial_stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-xenial-go_agent
    version_family: 651.50

- name: hourly_trigger
  type: time
  source:
    interval: 1h

- name: this_repo
  type: git
  source:
    branch: stress_testing
    uri: https://github.com/Smarsh/mongodb-boshrelease.git

jobs:
- name: deploy_release
  plan:
  - get: hourly_trigger
    trigger: true
  - get: mongodb_release
  - get: xenial_stemcell
  - get: old_xenial_stemcell
  - get: this_repo
    trigger: true
  - task: run_tests
    file: this_repo/ci_stress_testing/tasks/system_tests.yml
    timeout: 55m

