---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: mongodb_bosh_release
- name: mongodb_bosh_release_version

outputs:
- name: release_tarball

run:
  path: mongodb_bosh_release_git/ci_release_pipeline/tasks/create_release.sh
