---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: mongodb_bosh_release_git
- name: mongodb_release
- name: old_xenial_stemcell
- name: xenial_stemcell

run:
  path: mongodb_bosh_release_git/ci_release_pipeline/tasks/system_test.sh
